
import Clientes.Cliente;
import Clientes.ClientesDAO;
import java.awt.Component;
import java.awt.Graphics;
import java.awt.Insets;
import java.io.BufferedReader;
import java.io.EOFException;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.border.Border;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author DAM2
 */
public class Login extends javax.swing.JFrame {

    private static final String RAIZBUCKET = "E:/DAM2/DI";

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        getContentPane().setBackground(new java.awt.Color(53, 114, 239));
        etiquetaUserIncorrecto.setVisible(false);
        campoContraseniaLogin.setBorder(BorderFactory.createEmptyBorder(0, 0, 0, 0));
        campoCorreoLogin.setBorder(BorderFactory.createEmptyBorder(0, 0, 0, 0));
        botonLogin.setBorder(BorderFactory.createEmptyBorder(0, 0, 0, 0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        campoCorreoLogin = new javax.swing.JTextField();
        campoContraseniaLogin = new javax.swing.JPasswordField();
        botonLogin = new javax.swing.JButton();
        aquivaellogo = new javax.swing.JPanel();
        logotipo = new javax.swing.JLabel();
        etiquetaUserIncorrecto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(53, 114, 239));
        setMinimumSize(new java.awt.Dimension(620, 620));

        campoCorreoLogin.setText("Usuario");
        campoCorreoLogin.setPreferredSize(new java.awt.Dimension(145, 22));
        campoCorreoLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCorreoLoginActionPerformed(evt);
            }
        });

        campoContraseniaLogin.setText("contraseña");
        campoContraseniaLogin.setPreferredSize(new java.awt.Dimension(145, 22));
        campoContraseniaLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoContraseniaLoginActionPerformed(evt);
            }
        });

        botonLogin.setBackground(new java.awt.Color(2, 34, 57));
        botonLogin.setForeground(new java.awt.Color(255, 255, 255));
        botonLogin.setText("Login");
        botonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLoginActionPerformed(evt);
            }
        });

        aquivaellogo.setBackground(new java.awt.Color(53, 114, 239));

        logotipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo.png"))); // NOI18N
        logotipo.setLabelFor(logotipo);
        logotipo.setToolTipText("EnterCloud");

        javax.swing.GroupLayout aquivaellogoLayout = new javax.swing.GroupLayout(aquivaellogo);
        aquivaellogo.setLayout(aquivaellogoLayout);
        aquivaellogoLayout.setHorizontalGroup(
            aquivaellogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, aquivaellogoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logotipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        aquivaellogoLayout.setVerticalGroup(
            aquivaellogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, aquivaellogoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logotipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        etiquetaUserIncorrecto.setText("Usuario o contraseña incorrectos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(135, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(campoCorreoLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoContraseniaLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aquivaellogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiquetaUserIncorrecto)
                    .addComponent(botonLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(135, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(aquivaellogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(campoCorreoLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoContraseniaLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(botonLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(etiquetaUserIncorrecto)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoContraseniaLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoContraseniaLoginActionPerformed
        // TODO add your handling code here:
        botonLoginActionPerformed(evt);
    }//GEN-LAST:event_campoContraseniaLoginActionPerformed
    private static boolean correoCorrecto(String correo, String contra) {
        BufferedReader fich = null;
        String linea;
        boolean existeCombo = false;
        try {
            fich = new BufferedReader(new InputStreamReader(new FileInputStream("clientes.txt")));
            linea = fich.readLine();
            while (linea != null && !existeCombo) {
                existeCombo = linea.equals(correo + ":" + contra);
                linea = fich.readLine();
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            if (fich != null) {
                try {
                    fich.close();
                } catch (IOException ex) {
                    Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }

        return existeCombo;
    }

    private void campoCorreoLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCorreoLoginActionPerformed
        // TODO add your handling code here:
        botonLoginActionPerformed(evt);

    }//GEN-LAST:event_campoCorreoLoginActionPerformed

    private void botonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLoginActionPerformed
        // TODO add your handling code here:
        boolean esValido;
        String correo = null, pass;
        try {
            correo = campoCorreoLogin.getText();
            pass = new String(campoContraseniaLogin.getPassword());
            esValido = correoCorrecto(correo, pass);
        } catch (NullPointerException e) {
            esValido = false;
        }
        etiquetaUserIncorrecto.setVisible(!esValido);
        this.setVisible(!esValido);
        if (esValido) {
            try {
                irAInicio(correo);
            } catch (IOException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_botonLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel aquivaellogo;
    private javax.swing.JButton botonLogin;
    private javax.swing.JPasswordField campoContraseniaLogin;
    private javax.swing.JTextField campoCorreoLogin;
    private javax.swing.JLabel etiquetaUserIncorrecto;
    private javax.swing.JLabel logotipo;
    // End of variables declaration//GEN-END:variables

    private void irAInicio(String correo) throws IOException {
        Cliente c = null;
        ClientesDAO fich = null;
        try {
            fich = new ClientesDAO("Clientes.dat", "r");
            try {
                while (true) {
                    c = fich.leer();
                    if (c.getCorreo().equals(correo)) {
                        break;
                    }
                }
            } catch (EOFException eof) {
                c = null;
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            if (fich != null) {
                try {
                    fich.cerrar();
                } catch (IOException e) {
                    System.err.println("Error al cerrar: " + e.getMessage());
                    e.printStackTrace();
                }
            }
        }
        if (c != null) {

            File raizUser = new File((RAIZBUCKET + "/" + c.getId()).replace('/', File.separatorChar));
            if (!raizUser.exists()) {
                if (!raizUser.mkdir()) {
                    throw new IOException("No se ha podido crear la raiz del usuario: "+c.getId());
                }
            }
            new Inicio(c).setVisible(true);
            this.setVisible(false);
        } else {
            System.err.println("No se ha encontrado el cliente: " + correo + " en Clientes.dat");
        }
    }
}
